service.vgroupMapping.auth-service-group=default
service.vgroupMapping.broadcast-service-group=default
service.vgroupMapping.distribution-service-group=default
service.vgroupMapping.goods-service-group=default
service.vgroupMapping.im-service-group=default
service.vgroupMapping.order-service-group=default
service.vgroupMapping.payment-service-group=default
service.vgroupMapping.promotion-service-group=default
service.vgroupMapping.resource-service-group=default
service.vgroupMapping.statistics-service-group=default
service.vgroupMapping.supplier-service-group=default
service.vgroupMapping.system-service-group=default
